### ISSUE TITLE
'omegaconf.errors.ConfigAttributeError: Missing key forest_regions' when trying to evaluate on the provided FOR-instance dataset using eval.py    

### ISSUE THREAD

**Issue by JiaxingEl99** [prs-eth/PanopticSegForLargeScalePointCloud#12]
Hi, 
I tried to see the evaluation results using the pretrained model on FOR-instance. The command is 'python eval.py'. But enconterred the following error.  I tried to add values to 'forest_regions' in treeins_rad8.yaml as follows, but it still didn't work.  What might be the reason?

forest_regions: ['CULS','NIBIO','NIBIO2','RMIT','SCION','TUWIEN']          
fold: ['/home/zhan5404/PanopticSeg/data/treeinsfused/raw/CULS/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/NIBIO/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/NIBIO2/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/RMIT/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/SCION/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/TUWIEN/']  

  
File "eval.py", line 14, in main
    trainer = Trainer(cfg)
  File "/home/zhan5404/PanopticSeg/torch_points3d/trainer.py", line 48, in __init__
    self._initialize_trainer()
  File "/home/zhan5404/PanopticSeg/torch_points3d/trainer.py", line 90, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._checkpoint.data_config)
  File "/home/zhan5404/PanopticSeg/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/home/zhan5404/PanopticSeg/torch_points3d/datasets/panoptic/treeins.py", line 633, in __init__
    forest_regions=self.dataset_opt.forest_regions,  # @Treeins
omegaconf.errors.ConfigAttributeError: Missing key forest_regions
    full_key: data.forest_regions
    object_type=dict

**Comment by bxiang233** [comment]
> Hi, I tried to see the evaluation results using the pretrained model on FOR-instance. The command is 'python eval.py'. But enconterred the following error. I tried to add values to 'forest_regions' in treeins_rad8.yaml as follows, but it still didn't work. What might be the reason?
> 
> forest_regions: ['CULS','NIBIO','NIBIO2','RMIT','SCION','TUWIEN'] fold: ['/home/zhan5404/PanopticSeg/data/treeinsfused/raw/CULS/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/NIBIO/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/NIBIO2/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/RMIT/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/SCION/','/home/zhan5404/PanopticSeg/data/treeinsfused/raw/TUWIEN/']
> 
> File "eval.py", line 14, in main trainer = Trainer(cfg) File "/home/zhan5404/PanopticSeg/torch_points3d/trainer.py", line 48, in **init** self._initialize_trainer() File "/home/zhan5404/PanopticSeg/torch_points3d/trainer.py", line 90, in _initialize_trainer self._dataset: BaseDataset = instantiate_dataset(self._checkpoint.data_config) File "/home/zhan5404/PanopticSeg/torch_points3d/datasets/dataset_factory.py", line 46, in instantiate_dataset dataset = dataset_cls(dataset_config) File "/home/zhan5404/PanopticSeg/torch_points3d/datasets/panoptic/treeins.py", line 633, in **init** forest_regions=self.dataset_opt.forest_regions, # @treeins omegaconf.errors.ConfigAttributeError: Missing key forest_regions full_key: data.forest_regions object_type=dict

Hi, here is the solution:
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/issues/10#issuecomment-2091561194

**Comment by JiaxingEl99** [comment]
Hello, 
Thank you very much for your reply. 
However, I followed suggestions 1,2,3, and still got the following errorr:  

__(PanopSeg) zhan5404@idif002:~/PanopticSeg$ python eval.py
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
eval.py:6: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="eval")
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'eval': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/hydra/core/default_element.py:124: UserWarning: In 'visualization/eval': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2024-09-17 11:37:33,933][torch_points3d.trainer][INFO] - DEVICE : cuda
[2024-09-17 11:37:34,449][torch_points3d.metrics.model_checkpoint][INFO] - Loading checkpoint from /home/zhan5404/PanopticSeg/outputs/PointGroup-PAPER.pt
Error executing job with overrides: []
Traceback (most recent call last):
  File "eval.py", line 12, in main
    trainer = Trainer(cfg)
  File "/home/zhan5404/PanopticSeg/torch_points3d/trainer.py", line 48, in __init__
    self._initialize_trainer()
  File "/home/zhan5404/PanopticSeg/torch_points3d/trainer.py", line 90, in _initialize_trainer
    self._dataset: BaseDataset = instantiate_dataset(self._checkpoint.data_config)
  File "/home/zhan5404/PanopticSeg/torch_points3d/datasets/dataset_factory.py", line 45, in instantiate_dataset
    dataset = dataset_cls(dataset_config)
  File "/home/zhan5404/PanopticSeg/torch_points3d/datasets/panoptic/treeins.py", line 631, in __init__
    forest_regions=self.dataset_opt.forest_regions,  # @Treeins
omegaconf.errors.ConfigAttributeError: Missing key forest_regions
    full_key: data.forest_regions
    object_type=dict
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace._

I have two more questions: 

1.  in the evaluation process (inference on FOR-Instance dataset with pre-trained model ), how do I choose whether to do semantic segmentation or instacne segmentation?  

2. In training, anything needs to be changed in the provided commands:  'python train.py task=panoptic data=panoptic/treeins_rad8 models=panoptic/area4_ablation_3heads_5 model_name=PointGroup-PAPER training=treeins job_name=treeins_my_first_run'   

(PanopSeg) zhan5404@idif002:~/PanopticSeg$ python train.py task=panoptic data=panoptic/treeins_rad8 models=panoptic/area4_ablation_3heads_5 model_name=PointGroup-PAPER training=treeins job_name=treeins_my_first_run
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
train.py:7: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="config")
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/opt/anaconda/envs/PanopSeg/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:415: UserWarning: In config: Invalid overriding of hydra/output:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
In 'config': Could not find 'data/panoptic/treeins_rad8'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/zhan5404/PanopticSeg/conf
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
