### ISSUE TITLE
AttributeError: 'PanopticTracker' object has no attribute 'spheres_count'

### ISSUE THREAD

**Issue by liangwenge740** [prs-eth/PanopticSegForLargeScalePointCloud#13]
Firstly, thank you for providing me with the code and data for my learning.But I encountered the following problem:

pre_collate_transform = Compose([
    SaveOriginalPosId,
    GridSampling3D(grid_size=0.2, quantize_coords=False, mode=last),
])
Size of train_dataset = 0
Size of test_dataset = 602
Size of val_dataset = 0
Batch size = 1
[2024-07-17 16:38:36,812][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets:  ['test'] 
[2024-07-17 16:38:36,812][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  None 
  0%|                                                   | 0/602 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 22, in <module>
    main()
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "eval.py", line 14, in main
    trainer.eval(stage_name = "test")
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 181, in eval
    self._test_epoch(epoch, "test")
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 262, in _test_epoch
    self._tracker.track(self._model, data=data, **self.tracker_options)
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 343, in track
    if self.spheres_count == self._dataset.test_data_num_spheres[self.cloud_count]:
AttributeError: 'PanopticTracker' object has no attribute 'spheres_count'

May I ask how to solve this problem？

**Comment by bxiang233** [comment]
> Firstly, thank you for providing me with the code and data for my learning.But I encountered the following problem:
> 
> pre_collate_transform = Compose([ SaveOriginalPosId, GridSampling3D(grid_size=0.2, quantize_coords=False, mode=last), ]) Size of train_dataset = 0 Size of test_dataset = 602 Size of val_dataset = 0 Batch size = 1 [2024-07-17 16:38:36,812][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets: ['test'] [2024-07-17 16:38:36,812][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset: None 0%| | 0/602 [00:00<?, ?it/s] Traceback (most recent call last): File "eval.py", line 22, in main() File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main _run_hydra( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra run_and_report( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report raise ex File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report return func() File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in lambda: hydra.run( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run return run_job( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job ret.return_value = task_function(task_cfg) File "eval.py", line 14, in main trainer.eval(stage_name = "test") File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 181, in eval self._test_epoch(epoch, "test") File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 262, in _test_epoch self._tracker.track(self._model, data=data, **self.tracker_options) File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 343, in track if self.spheres_count == self._dataset.test_data_num_spheres[self.cloud_count]: AttributeError: 'PanopticTracker' object has no attribute 'spheres_count'
> 
> May I ask how to solve this problem？

Hi, could you please try to uncomment this line?
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/blob/a53f2faee444725f997189d19a46eb14065ece2c/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py#L291C9-L291C10

And if you don't want to output the visual results:
Try to comment these lines:
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/blob/a53f2faee444725f997189d19a46eb14065ece2c/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py#L307C9-L344C75

**Comment by liangwenge740** [comment]
Hello,because I need to visualization,so I try to uncomment line 291, but another problem happen:

Size of train_dataset = 0
Size of test_dataset = 602
Size of val_dataset = 0
Batch size = 1
[2024-07-17 17:49:37,679][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets:  ['test'] 
[2024-07-17 17:49:37,679][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  None 
  0%|                                                   | 0/602 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 22, in <module>
    main()
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "eval.py", line 14, in main
    trainer.eval(stage_name = "test")
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 181, in eval
    self._test_epoch(epoch, "test")
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 262, in _test_epoch
    self._tracker.track(self._model, data=data, **self.tracker_options)
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 291, in track
    self._dump_visuals_fortest(outputs, originids, valid_c_idx)
  File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 309, in _dump_visuals_fortest
    for i, cluster in enumerate(outputs.clusters):
TypeError: 'NoneType' object is not iterable

**Comment by bxiang233** [comment]
> Hello,because I need to visualization,so I try to uncomment line 291, but another problem happen:
> 
> Size of train_dataset = 0 Size of test_dataset = 602 Size of val_dataset = 0 Batch size = 1 [2024-07-17 17:49:37,679][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets: ['test'] [2024-07-17 17:49:37,679][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset: None 0%| | 0/602 [00:00<?, ?it/s] Traceback (most recent call last): File "eval.py", line 22, in main() File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main _run_hydra( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra run_and_report( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report raise ex File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report return func() File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in lambda: hydra.run( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run return run_job( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job ret.return_value = task_function(task_cfg) File "eval.py", line 14, in main trainer.eval(stage_name = "test") File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 181, in eval self._test_epoch(epoch, "test") File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/trainer.py", line 262, in _test_epoch self._tracker.track(self._model, data=data, **self.tracker_options) File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 291, in track self._dump_visuals_fortest(outputs, originids, valid_c_idx) File "/home/lwg/PanopticSegForLargeScalePointCloud-main/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 309, in _dump_visuals_fortest for i, cluster in enumerate(outputs.clusters): TypeError: 'NoneType' object is not iterable

The visualizations in this function are just some intermediate results. You can comment them out. The code for generating the final visualization results is here:
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/blob/a53f2faee444725f997189d19a46eb14065ece2c/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py#L564

And could you please have a look at this issue?
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/issues/10#issuecomment-2091561194

**Comment by liangwenge740** [comment]
Hello ,I look the issue you send me and modify this code ,it can run but remain have problem

Size of train_dataset = 0
Size of test_dataset = 602
Size of val_dataset = 0
Batch size = 1
[2024-07-17 20:10:03,985][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets:  ['test'] 
[2024-07-17 20:10:03,985][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset:  None 
 93%|▉| 562/602 [08:33<00:21,  1.89it/s, test_F1=0.738, test_Iacc=0.852, test_ac/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/sklearn/cluster/_mean_shift.py:246: UserWarning: Binning data failed with provided bin_size=0.600000, using data points as seeds.
  warnings.warn(
100%|█| 602/602 [09:17<00:00,  1.08it/s, test_F1=0.724, test_Iacc=0.835, test_ac
out
Traceback (most recent call last):
  File "eval.py", line 22, in <module>
    main()
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "eval.py", line 14, in main
    trainer.eval(stage_name = "test")
  File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/trainer.py", line 181, in eval
    self._test_epoch(epoch, "test")
  File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/trainer.py", line 275, in _test_epoch
    self._finalize_epoch(epoch)
  File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/trainer.py", line 184, in _finalize_epoch
    self._tracker.finalise(**self.tracker_options)
  File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 665, in finalise
    self.dataset.to_eval_ply(
AttributeError: 'PanopticTracker' object has no attribute 'dataset'

**Comment by bxiang233** [comment]
> Hello ,I look the issue you send me and modify this code ,it can run but remain have problem
> 
> Size of train_dataset = 0 Size of test_dataset = 602 Size of val_dataset = 0 Batch size = 1 [2024-07-17 20:10:03,985][torch_points3d.datasets.base_dataset][INFO] - Available stage selection datasets: ['test'] [2024-07-17 20:10:03,985][torch_points3d.datasets.base_dataset][INFO] - The models will be selected using the metrics on following dataset: None 93%|▉| 562/602 [08:33<00:21, 1.89it/s, test_F1=0.738, test_Iacc=0.852, test_ac/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/sklearn/cluster/_mean_shift.py:246: UserWarning: Binning data failed with provided bin_size=0.600000, using data points as seeds. warnings.warn( 100%|█| 602/602 [09:17<00:00, 1.08it/s, test_F1=0.724, test_Iacc=0.835, test_ac out Traceback (most recent call last): File "eval.py", line 22, in main() File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main _run_hydra( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra run_and_report( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report raise ex File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report return func() File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in lambda: hydra.run( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run return run_job( File "/home/lwg/anaconda3/envs/instance/lib/python3.8/site-packages/hydra/core/utils.py", line 128, in run_job ret.return_value = task_function(task_cfg) File "eval.py", line 14, in main trainer.eval(stage_name = "test") File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/trainer.py", line 181, in eval self._test_epoch(epoch, "test") File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/trainer.py", line 275, in _test_epoch self._finalize_epoch(epoch) File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/trainer.py", line 184, in _finalize_epoch self._tracker.finalise(**self.tracker_options) File "/home/lwg/PanopticSegForLargeScalePointCloud/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py", line 665, in finalise self.dataset.to_eval_ply( AttributeError: 'PanopticTracker' object has no attribute 'dataset'

Please see this line: dataset->_dataset
https://github.com/prs-eth/PanopticSegForLargeScalePointCloud/blob/7f57b9b2dbb478b996aeff891cded51441f2917d/torch_points3d/metrics/panoptic_tracker_pointgroup_treeins.py#L665

**Comment by liangwenge740** [comment]
Thank for your help,I have successfully solved the problem and achieved good results
